Another attempt to fix result code

diff --git a/.bin/test b/.bin/test
--- a/.bin/test
+++ b/.bin/test
@@ -7,14 +7,14 @@ set -o pipefail && xcodebuild clean test -workspace BookishModel.xcworkspace -sc
 MAC_RESULT=$?
 
 echo
-echo Testing Mobile
+echo "Testing Mobile"
 
 rm -rf .build/Mobile.xcresult .build/Mobile.log
 set -o pipefail && xcodebuild clean test -workspace BookishModel.xcworkspace -scheme BookishModelMobile -destination "name=iPhone 6" -enableCodeCoverage YES -resultBundlePath .build/Mobile.xcresult | tee .build/Mobile.log | xcpretty -f `xcpretty-travis-formatter`
 MOBILE_RESULT=$?
 
 echo
-echo Coverage
+echo "Coverage"
 
 .bin/coverage
 COVERAGE_RESULT=$?
@@ -22,4 +22,8 @@ COVERAGE_RESULT=$?
 echo
 echo Done
 
-exit $MAC_RESULT || $MOBILE_RESULT || $COVERAGE_RESULT
+if [[ ($MAC_RESULT != 0) || ($MOBILE_RESULT != 0) || ($COVERAGE_RESULT != 0) ]]
+then
+    echo "Tests failed."
+    exit 1
+fi
